# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tsuharesu
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website, where I put some development codes and some personal
  random posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tsuharesu.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: none
twitter:
  username: tsuharesu
social:
  name: Tsuharesu
  links:
    - https://twitter.com/tsuharesu
    - https://github.com/tsuharesu
    - https://instagram.com/tsuharesu
    - https://tsuharesu.tumblr.com
    - https://medium.com/@tsuharesu
    - https://linkedin.com/in/thalesphelipe
google_analytics: "UA-18519572-3"
disqus: "tsuharesu"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Style settings
sass:
    style: compressed
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: java

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "posts"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
